/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PalPanel {
    }
    interface PalPanelStackHeader {
        "active": boolean;
        "title": string;
    }
    interface PalPanelsContainer {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPalPanelElement extends Components.PalPanel, HTMLStencilElement {
    }
    var HTMLPalPanelElement: {
        prototype: HTMLPalPanelElement;
        new (): HTMLPalPanelElement;
    };
    interface HTMLPalPanelStackHeaderElement extends Components.PalPanelStackHeader, HTMLStencilElement {
    }
    var HTMLPalPanelStackHeaderElement: {
        prototype: HTMLPalPanelStackHeaderElement;
        new (): HTMLPalPanelStackHeaderElement;
    };
    interface HTMLPalPanelsContainerElement extends Components.PalPanelsContainer, HTMLStencilElement {
    }
    var HTMLPalPanelsContainerElement: {
        prototype: HTMLPalPanelsContainerElement;
        new (): HTMLPalPanelsContainerElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "pal-panel": HTMLPalPanelElement;
        "pal-panel-stack-header": HTMLPalPanelStackHeaderElement;
        "pal-panels-container": HTMLPalPanelsContainerElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PalPanel {
    }
    interface PalPanelStackHeader {
        "active"?: boolean;
        "onDragTab"?: (event: CustomEvent<boolean>) => void;
        "title"?: string;
    }
    interface PalPanelsContainer {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "pal-panel": PalPanel;
        "pal-panel-stack-header": PalPanelStackHeader;
        "pal-panels-container": PalPanelsContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pal-panel": LocalJSX.PalPanel & JSXBase.HTMLAttributes<HTMLPalPanelElement>;
            "pal-panel-stack-header": LocalJSX.PalPanelStackHeader & JSXBase.HTMLAttributes<HTMLPalPanelStackHeaderElement>;
            "pal-panels-container": LocalJSX.PalPanelsContainer & JSXBase.HTMLAttributes<HTMLPalPanelsContainerElement>;
        }
    }
}
